name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

env:
  DOCMAKER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TOOLBOX_FILE: release/DocExample.mltbx

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: matlab-actions/setup-matlab@v3
        with:
          release: R2026a
      - uses: matlab-actions/run-command@v3
        with:
          command: |
            fileName = websave("MATLAB_DocMaker.mtlbx","https://github.com/mathworks/docmaker/releases/latest/download/MATLAB_DocMaker.mltbx");
            matlab.addons.install(fileName,"overwrite",true);
      - uses: matlab-actions/run-build@v3
      - uses: actions/upload-artifact@v7
        with:
          name: toolbox
          path: ${{ env.TOOLBOX_FILE }}
      - name: Release toolbox
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: ${{ env.TOOLBOX_FILE }}
